//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foms.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foms.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap Admin_Background {
            get {
                object obj = ResourceManager.GetObject("Admin_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Admin_Background_180 {
            get {
                object obj = ResourceManager.GetObject("Admin_Background_180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap arrow_down_small {
            get {
                object obj = ResourceManager.GetObject("arrow_down_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bouton_report_standart_1281 {
            get {
                object obj = ResourceManager.GetObject("bouton_report_standart_1281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bouton_report_standart_321 {
            get {
                object obj = ResourceManager.GetObject("bouton_report_standart_321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bouton_report_standart_641 {
            get {
                object obj = ResourceManager.GetObject("bouton_report_standart_641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap confirm_contract_1_16x16 {
            get {
                object obj = ResourceManager.GetObject("confirm_contract_1_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap croix {
            get {
                object obj = ResourceManager.GetObject("croix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dowarrow {
            get {
                object obj = ResourceManager.GetObject("dowarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap en_small {
            get {
                object obj = ResourceManager.GetObject("en_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap financial_information_bouton_files_16x16 {
            get {
                object obj = ResourceManager.GetObject("financial_information_bouton files_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap flecheBH {
            get {
                object obj = ResourceManager.GetObject("flecheBH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap flecheHB {
            get {
                object obj = ResourceManager.GetObject("flecheHB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap fr_small {
            get {
                object obj = ResourceManager.GetObject("fr_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap languages {
            get {
                object obj = ResourceManager.GetObject("languages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pastille_groupe {
            get {
                object obj = ResourceManager.GetObject("pastille_groupe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pastille_report {
            get {
                object obj = ResourceManager.GetObject("pastille_report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pastille_report1 {
            get {
                object obj = ResourceManager.GetObject("pastille_report1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap progress {
            get {
                object obj = ResourceManager.GetObject("progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ru_small {
            get {
                object obj = ResourceManager.GetObject("ru_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap run {
            get {
                object obj = ResourceManager.GetObject("run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Spanish_Flag1 {
            get {
                object obj = ResourceManager.GetObject("Spanish Flag1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SuperAdmin_Background {
            get {
                object obj = ResourceManager.GetObject("SuperAdmin_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SuperAdmin_Background_180 {
            get {
                object obj = ResourceManager.GetObject("SuperAdmin_Background_180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap thame1_1_database {
            get {
                object obj = ResourceManager.GetObject("thame1.1_database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_close {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_delete {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_down {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_new {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_next {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_previous {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_print {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_save {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_stop {
            get {
                object obj = ResourceManager.GetObject("theme1_1_bouton_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_up {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_bouton_validity {
            get {
                object obj = ResourceManager.GetObject("theme1.1_bouton_validity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_doc {
            get {
                object obj = ResourceManager.GetObject("theme1.1_doc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_export {
            get {
                object obj = ResourceManager.GetObject("theme1.1_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_fond_bouton {
            get {
                object obj = ResourceManager.GetObject("theme1.1_fond_bouton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_fond_gris {
            get {
                object obj = ResourceManager.GetObject("theme1.1_fond_gris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_fond_gris_180 {
            get {
                object obj = ResourceManager.GetObject("theme1.1_fond_gris_180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_fond_vert {
            get {
                object obj = ResourceManager.GetObject("theme1.1_fond_vert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_import {
            get {
                object obj = ResourceManager.GetObject("theme1.1_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_pastille_contrat {
            get {
                object obj = ResourceManager.GetObject("theme1.1_pastille_contrat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_pastille_option {
            get {
                object obj = ResourceManager.GetObject("theme1.1_pastille_option", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_pastille_personne {
            get {
                object obj = ResourceManager.GetObject("theme1.1_pastille_personne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_pastille_produit {
            get {
                object obj = ResourceManager.GetObject("theme1.1_pastille_produit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_restore_data {
            get {
                object obj = ResourceManager.GetObject("theme1.1_restore_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_search {
            get {
                object obj = ResourceManager.GetObject("theme1.1_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap theme1_1_view {
            get {
                object obj = ResourceManager.GetObject("theme1.1_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap uparrow {
            get {
                object obj = ResourceManager.GetObject("uparrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
